import React, { useEffect, useMemo, useState } from 'react';
import { Landmark, Upload, History, Search, CheckCircle2, AlertTriangle, FileText, RefreshCw, WandSparkles, XCircle } from 'lucide-react';
import { api } from '../../services/api';

const money=(v:any)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const date=(v:any)=>v?new Date(v).toLocaleDateString('pt-BR'):'—';

export const FinanceReconciliationModule: React.FC = () => {
  const [accounts,setAccounts]=useState<any[]>([]); const [accountId,setAccountId]=useState('');
  const [ledger,setLedger]=useState<any[]>([]); const [statement,setStatement]=useState<any[]>([]); const [summary,setSummary]=useState<any>({});
  const [history,setHistory]=useState<any[]>([]); const [tab,setTab]=useState<'importar'|'extrato'|'movimentos'|'historico'>('importar');
  const [file,setFile]=useState<File|null>(null); const [fileText,setFileText]=useState(''); const [preview,setPreview]=useState<any[]>([]);
  const [search,setSearch]=useState(''); const [status,setStatus]=useState('ALL'); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
  const [suggestions,setSuggestions]=useState<Record<string,any[]>>({});

  const load=async(id?:string)=>{ const a=await api.getBankAccounts(); setAccounts(a); const selected=id||accountId||a[0]?.id||''; if(selected){setAccountId(selected); const [l,s]=await Promise.all([api.getBankTransactions(selected),api.getOfxStatement(selected,status).catch(()=>({transactions:[],summary:{}}))]); setLedger(l);setStatement(s.transactions||[]);setSummary(s.summary||{});} setHistory(await api.getBankReconciliations()); };
  useEffect(()=>{load();},[]);
  useEffect(()=>{if(accountId) Promise.all([api.getBankTransactions(accountId),api.getOfxStatement(accountId,status).catch(()=>({transactions:[],summary:{}}))]).then(([l,s])=>{setLedger(l);setStatement(s.transactions||[]);setSummary(s.summary||{});});},[accountId,status]);

  const selectFile=async(f:File)=>{setFile(f);const text=await f.text();setFileText(text);const blocks=text.match(/<STMTTRN>[\s\S]*?(?=<STMTTRN>|<\/BANKTRANLIST>|$)/gi)||[];const val=(b:string,t:string)=>b.match(new RegExp(`<${t}>([^<\\r\\n]+)`,'i'))?.[1]?.trim()||'';setPreview(blocks.slice(0,50).map((b,i)=>({id:i,date:val(b,'DTPOSTED').slice(0,8),memo:val(b,'MEMO')||val(b,'NAME'),fitid:val(b,'FITID'),amount:Number(val(b,'TRNAMT')||0)})));setMessage('');};
  const importFile=async()=>{if(!file||!accountId)return;setBusy(true);setMessage('');try{const r=await api.importOfx(accountId,file.name,fileText);setMessage(`Importação concluída: ${r.inserted} movimento(s). ${r.duplicates||0} duplicidade(s) ignorada(s).`);setFile(null);setFileText('');setPreview([]);setTab('extrato');await load(accountId);}catch(e:any){setMessage(e.message);}finally{setBusy(false);}};
  const findSuggestions=async(id:string)=>{try{setSuggestions(x=>({...x,[id]:[]}));const rows=await api.getOfxSuggestions(id);setSuggestions(x=>({...x,[id]:rows}));}catch(e:any){setMessage(e.message);}};
  const reconcile=async(stId:string,btId:string)=>{setBusy(true);try{await api.reconcileOfx(stId,btId);setMessage('Movimento conciliado com sucesso e registrado na auditoria.');await load(accountId);}catch(e:any){setMessage(e.message);}finally{setBusy(false);}};
  const divergence=async(id:string)=>{const reason=window.prompt('Informe o motivo da divergência:');if(!reason)return;setBusy(true);try{await api.markOfxDivergence(id,reason);setMessage('Divergência registrada.');await load(accountId);}catch(e:any){setMessage(e.message);}finally{setBusy(false);}};
  const filtered=useMemo(()=>ledger.filter(t=>JSON.stringify(t).toLowerCase().includes(search.toLowerCase())),[ledger,search]);
  const stat=(k:string)=>summary?.[k]||{qty:0,total:0};

  return <div className="space-y-5">
    <div className="flex flex-col md:flex-row md:items-end md:justify-between gap-3 border-b border-slate-200 pb-4"><div><h1 className="text-xl font-black text-slate-900">Conciliação Bancária</h1><p className="text-xs text-slate-500 mt-1">OFX real → FITID → correspondência → conciliação → auditoria.</p></div><select className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-xs" value={accountId} onChange={e=>setAccountId(e.target.value)}>{accounts.map(a=><option key={a.id} value={a.id}>{a.bank_name||a.bankName} • {a.agency}/{a.account_number||a.accountNumber}</option>)}</select></div>
    {message&&<div className={`rounded-lg border px-4 py-3 text-xs font-semibold ${message.toLowerCase().includes('sucesso')||message.includes('concluída')?'border-emerald-200 bg-emerald-50 text-emerald-800':'border-amber-200 bg-amber-50 text-amber-900'}`}>{message}</div>}
    <div className="grid grid-cols-1 md:grid-cols-3 gap-3"><div className="rounded-xl border bg-white p-4"><span className="text-[10px] font-bold uppercase text-slate-400">OFX pendente</span><div className="text-2xl font-black text-amber-700 mt-1">{stat('PENDENTE').qty}</div><div className="text-xs text-slate-500">{money(stat('PENDENTE').total)}</div></div><div className="rounded-xl border bg-white p-4"><span className="text-[10px] font-bold uppercase text-slate-400">Conciliado</span><div className="text-2xl font-black text-emerald-700 mt-1">{stat('CONCILIADO').qty}</div><div className="text-xs text-slate-500">{money(stat('CONCILIADO').total)}</div></div><div className="rounded-xl border bg-white p-4"><span className="text-[10px] font-bold uppercase text-slate-400">Divergências</span><div className="text-2xl font-black text-rose-700 mt-1">{stat('DIVERGENTE').qty}</div><div className="text-xs text-slate-500">{money(stat('DIVERGENTE').total)}</div></div></div>
    <div className="flex gap-2 border-b border-slate-200 dark:border-slate-800 overflow-auto">{[['importar','Importar OFX',Upload],['extrato','Extrato OFX',FileText],['movimentos','Ledger interno',Landmark],['historico','Histórico',History]].map(([k,l,I]:any)=><button key={k} onClick={()=>setTab(k)} className={`flex shrink-0 items-center gap-2 px-4 py-2.5 text-xs font-bold border-b-2 transition-all cursor-pointer ${tab===k?'border-emerald-600 dark:border-[#10b981] text-emerald-700 dark:text-[#10b981] font-bold dark:drop-shadow-[0_0_8px_rgba(16,185,129,0.85)]':'border-transparent text-slate-500 dark:text-emerald-400/80 hover:text-slate-800 dark:hover:text-[#10b981] dark:hover:drop-shadow-[0_0_6px_rgba(16,185,129,0.6)]'}`}><I className="h-4 w-4"/>{l}</button>)}</div>
    {tab==='importar'&&<div className="rounded-xl border bg-white p-5 space-y-4"><div className="rounded-lg border border-dashed border-slate-300 bg-slate-50 p-8 text-center"><Upload className="h-8 w-8 mx-auto text-blue-600 mb-2"/><h3 className="font-bold text-sm">Importar extrato bancário OFX</h3><p className="text-xs text-slate-500 mt-1">O arquivo será validado e gravado no backend. Arquivos repetidos e FITIDs já importados são bloqueados.</p><label className="inline-flex mt-4 cursor-pointer rounded-lg bg-blue-700 px-4 py-2 text-xs font-bold text-white">Selecionar arquivo<input type="file" accept=".ofx,.qfx" className="hidden" onChange={e=>e.target.files?.[0]&&selectFile(e.target.files[0])}/></label>{file&&<div className="mt-4"><p className="text-xs font-semibold">{file.name} • {preview.length} movimento(s) na prévia</p><button disabled={busy} onClick={importFile} className="mt-3 rounded-lg bg-emerald-700 px-4 py-2 text-xs font-bold text-white disabled:opacity-50">{busy?'Importando...':'Validar e importar no SEEK'}</button></div>}</div>{preview.length>0&&<div className="overflow-auto"><table className="w-full text-xs"><thead className="bg-slate-50"><tr><th className="p-2 text-left">Data</th><th className="text-left">Descrição</th><th className="text-left">FITID</th><th className="text-right pr-2">Valor</th></tr></thead><tbody>{preview.slice(0,12).map(x=><tr key={x.id} className="border-t"><td className="p-2">{x.date}</td><td>{x.memo||'—'}</td><td>{x.fitid||'—'}</td><td className="text-right pr-2 font-bold">{money(x.amount)}</td></tr>)}</tbody></table></div>}</div>}
    {tab==='extrato'&&<div className="rounded-xl border bg-white overflow-auto"><div className="p-3 border-b flex justify-between gap-2"><select value={status} onChange={e=>setStatus(e.target.value)} className="border rounded-lg px-3 py-2 text-xs"><option value="ALL">Todos os status</option><option value="PENDENTE">Pendentes</option><option value="CONCILIADO">Conciliados</option><option value="DIVERGENTE">Divergentes</option></select><button onClick={()=>load(accountId)}><RefreshCw className="h-4 w-4"/></button></div><table className="w-full text-xs"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Data</th><th className="text-left">Descrição</th><th className="text-left">FITID</th><th className="text-right">Valor</th><th className="text-left pl-4">Status / Ação</th></tr></thead><tbody>{statement.map((s:any)=><React.Fragment key={s.id}><tr className="border-t"><td className="p-3">{date(s.posted_at)}</td><td>{s.memo||s.name||'—'}</td><td>{s.fitid}</td><td className="text-right font-bold">{money(s.amount)}</td><td className="pl-4 py-2"><span className={`font-bold ${s.status==='CONCILIADO'?'text-emerald-700':s.status==='DIVERGENTE'?'text-rose-700':'text-amber-700'}`}>{s.status}</span>{s.status==='PENDENTE'&&<div className="flex gap-2 mt-1"><button disabled={busy} onClick={()=>findSuggestions(s.id)} className="inline-flex items-center gap-1 text-blue-700 font-bold"><WandSparkles className="h-3 w-3"/>Localizar</button><button disabled={busy} onClick={()=>divergence(s.id)} className="inline-flex items-center gap-1 text-rose-700"><XCircle className="h-3 w-3"/>Divergência</button></div>}{s.divergence_reason&&<div className="text-[10px] text-slate-500 mt-1">{s.divergence_reason}</div>}</td></tr>{suggestions[s.id]?.length>0&&<tr className="bg-blue-50/60"><td colSpan={5} className="p-3"><div className="text-[10px] font-bold uppercase text-blue-700 mb-2">Correspondências encontradas</div>{suggestions[s.id].slice(0,3).map((c:any)=><div key={c.id} className="flex flex-wrap items-center justify-between gap-2 border-t border-blue-100 py-2"><span>{date(c.transaction_date)} • {c.description} • <b>{money(c.amount)}</b></span><span className="flex items-center gap-3"><b>{c.score}%</b><button disabled={busy} onClick={()=>reconcile(s.id,c.id)} className="rounded bg-blue-700 text-white px-3 py-1 font-bold">Conciliar</button></span></div>)}</td></tr>}</React.Fragment>)}</tbody></table>{statement.length===0&&<div className="p-8 text-center text-xs text-slate-400">Nenhum movimento OFX importado para esta conta.</div>}</div>}
    {tab==='movimentos'&&<div className="rounded-xl border bg-white overflow-hidden"><div className="p-3 border-b flex items-center gap-2"><Search className="h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Pesquisar no ledger interno..." className="w-full outline-none text-xs"/></div><div className="overflow-auto"><table className="w-full text-xs"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Data</th><th className="text-left">Descrição</th><th>Tipo</th><th className="text-right">Valor</th><th className="text-center">Status</th></tr></thead><tbody>{filtered.map(t=><tr key={t.id} className="border-t"><td className="p-3">{date(t.transaction_date)}</td><td>{t.description}</td><td className="text-center">{t.type}</td><td className="text-right font-bold">{money(t.amount)}</td><td className="text-center">{t.reconciled?<span className="text-emerald-700 inline-flex gap-1"><CheckCircle2 className="h-4 w-4"/>Conciliado</span>:<span className="text-amber-700 inline-flex gap-1"><AlertTriangle className="h-4 w-4"/>Pendente</span>}</td></tr>)}</tbody></table></div></div>}
    {tab==='historico'&&<div className="rounded-xl border bg-white overflow-auto"><table className="w-full text-xs"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Período</th><th className="text-left">Conta</th><th className="text-right">Extrato</th><th className="text-right">Sistema</th><th className="text-right">Diferença</th><th>Status</th></tr></thead><tbody>{history.map((h:any)=><tr key={h.id} className="border-t"><td className="p-3">{h.period}</td><td>{h.bank_name||h.account_id}</td><td className="text-right">{money(h.statement_balance)}</td><td className="text-right">{money(h.system_balance)}</td><td className="text-right font-bold">{money(h.difference)}</td><td>{h.status}</td></tr>)}</tbody></table>{history.length===0&&<div className="p-8 text-center text-xs text-slate-400"><FileText className="h-8 w-8 mx-auto mb-2"/>Nenhuma conciliação registrada.</div>}</div>}
  </div>;
};
